USE [master]
GO

/****** Object:  Database [PRUEBA]    Script Date: 23/6/2020 21:32:59 ******/
CREATE DATABASE [PRUEBA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PRUEBA', FILENAME = N'D:\Dev\DATA\PRUEBA.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PRUEBA_log', FILENAME = N'L:\Dev\LOG\PRUEBA_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PRUEBA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PRUEBA] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PRUEBA] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PRUEBA] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PRUEBA] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PRUEBA] SET ARITHABORT OFF 
GO

ALTER DATABASE [PRUEBA] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PRUEBA] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PRUEBA] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PRUEBA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PRUEBA] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PRUEBA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PRUEBA] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PRUEBA] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PRUEBA] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PRUEBA] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PRUEBA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PRUEBA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PRUEBA] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PRUEBA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PRUEBA] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PRUEBA] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PRUEBA] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PRUEBA] SET RECOVERY FULL 
GO

ALTER DATABASE [PRUEBA] SET  MULTI_USER 
GO

ALTER DATABASE [PRUEBA] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PRUEBA] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PRUEBA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PRUEBA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PRUEBA] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PRUEBA] SET QUERY_STORE = OFF
GO

ALTER DATABASE [PRUEBA] SET  READ_WRITE 
GO


